
#RedisSearch: https://www.yuque.com/tianliuzhen/gs3ud6/cpqrt0ag67co3vpf#articleContentId
spring.data.redis.host=124.221.225.161
spring.data.redis.port=6389
#database 最后设置为0，如果设置其他值，初始化索引index时会报异常，Caused by: redis.clients.jedis.exceptions.JedisDataException: Cannot create index on db != 0
spring.data.redis.database=0

#spring.data.redis.host=127.0.0.1
#spring.data.redis.port=6379

#spring.data.redis.database=10 #rediSearch???db?= 0?????
#spring.data.redis.password=Sfb6RNsX+tyaVFENQg

#redisVectorstore配置
spring.ai.vectorstore.redis.index=test-tlz-index
spring.ai.vectorstore.redis.prefix=ai-docs:
#是否自动初始化index
spring.ai.vectorstore.redis.initialize-schema=true

