#es账密
spring.elasticsearch.uris=https://localhost:9200
spring.elasticsearch.username=admin
spring.elasticsearch.password=123456

#索引配置
spring.ai.vectorstore.elasticsearch.index-name=easy-agent-demo1
#自动初始化索引
spring.ai.vectorstore.elasticsearch.initialize-schema=true
#默认是 1536，不同的EmbeddingModel 维度不同 会报错，如果默认已生成需要删除重新建立，
# eg： [1:21843] failed to parse: The [dense_vector] field [embedding] in doc [document with id 'pJhiih1rAjwjhnub_0'] has more dimensions than defined in the mapping [1536]
spring.ai.vectorstore.elasticsearch.dimensions=2048


