spring.application.name=spring-ai

# ??????RedisSearch: https://www.yuque.com/tianliuzhen/gs3ud6/cpqrt0ag67co3vpf#articleContentId
spring.data.redis.host=124.221.225.161
spring.data.redis.port=6389
#spring.data.redis.database=10 #rediSearch???db?= 0?????
#spring.data.redis.password=Sfb6RNsX+tyaVFENQg

#redisVectorstore??
spring.ai.vectorstore.redis.index=test-tlz-index
spring.ai.vectorstore.redis.prefix=ai-docs:
#?????index
spring.ai.vectorstore.redis.initialize-schema=true
