spring:
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: qwen2.5:3b
          temperature: 0.7

---
spring:
  ai:
    openai:
      api-key: sk-cT6YTFBsX8qrmIYGrIB9tO5PtA0ea3onnfS38NMTNIuJ9mWm # 获取免费apiKey https://mp.weixin.qq.com/s?__biz=MzU0MzI3MzU1Ng==&mid=2247484719&idx=1&sn=33b4f623d421216fae26ddcae446e4da&chksm=fb0ca214cc7b2b0215d12a29ff091c5840798b8b15657212d248f73ae6b7c63b2fc28e72bf4a&scene=21#wechat_redirect
      base-url:  https://api.chatanywhere.tech #  https://api.openai.com（分为代理地址和直连地址）
