spring.application.name=spring-ai

# application-redis-config.properties
#spring.profiles.include=redis-config

spring.config.import=optional:classpath:/config/redis-config.properties,optional:classpath:/config/mysql-config.yml


logging.config=classpath:log4j2-spring.xml
# ???? springboot3 .log ??????
logging.file.path=F:/WorkSpace/MyGithub/easy-agent/log
logging.file.name=easy-name-log
