spring:
  autoconfigure:
    exclude:
      - org.springframework.ai.autoconfigure.vectorstore.redis.RedisVectorStoreAutoConfiguration
      - org.springframework.ai.retry.autoconfigure.SpringAiRetryAutoConfiguration
---


spring:
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: qwen2.5:3b  # 经过测试： qwen2.5:0.5b 因为体积小不够智能
          temperature: 0.7
      embedding:
        model: qwen2.5:3b # 默认模型是：org.springframework.ai.ollama.api.OllamaModel#MXBAI_EMBED_LARGE
---
spring:
  ai:
    openai: #感谢： https://github.com/chatanywhere/GPT_API_free?tab=readme-ov-file
      api-key: sk-cT6YTFBsX8qrmIYGrIB9tO5PtA0ea3onnfS38NMTNIuJ9mWm # 获取免费apiKey https://mp.weixin.qq.com/s?__biz=MzU0MzI3MzU1Ng==&mid=2247484719&idx=1&sn=33b4f623d421216fae26ddcae446e4da&chksm=fb0ca214cc7b2b0215d12a29ff091c5840798b8b15657212d248f73ae6b7c63b2fc28e72bf4a&scene=21#wechat_redirect
      base-url:  https://api.chatanywhere.tech #  https://api.openai.com（分为代理地址和直连地址）
      chat:
        options:   # 默认model是gpt-4o：org.springframework.ai.autoconfigure.openai.OpenAiChatProperties.DEFAULT_CHAT_MODEL
          model: gpt-4o #免费版支持gpt-4，一天3次；支持gpt-4o-mini，和gpt-3.5-turbo共享一天200次。
      image:
        enabled: true # 默认是开启的
        base-url:   https://api.chatanywhere.tech #可选地覆盖 spring.ai.openai.base-url 以提供特定于聊天的 url
        api-key: sk-cT6YTFBsX8qrmIYGrIB9tO5PtA0ea3onnfS38NMTNIuJ9mWm #可选地覆盖 spring.ai.openai.api-key 以提供特定于聊天的 api-key
---
spring:
  ai:
    deepseek: #感谢：硅基流动 https://cloud.siliconflow.cn/models
      api-key: sk-ewykgprysbswuqagkpbuglgodbxshtucznttazynawykgsds
      base-url: https://api.siliconflow.cn/
      chat:
        options:
          model: Qwen/QwQ-32B
        completions-path: /v1/chat/completions

---
spring:
  ai:
    dp: #感谢：硅基流动 https://cloud.siliconflow.cn/models
      api-key: sk-ewykgprysbswuqagkpbuglgodbxshtucznttazynawykgsds
      base-url: https://api.siliconflow.cn/
      chat:
        options:
          model: Qwen/QwQ-32B
        completions-path: /v1/chat/completions
