package com.aaa.springai.domain.DO;

import jakarta.persistence.*;

/**
 * 表名：ea_agent
*/
@Table(name = "`ea_agent`")
public class EaAgentDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ea_agent.id
     *
     * @mbg.generated Sat Jun 14 22:38:08 CST 2025
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ea_agent.agent_name
     *
     * @mbg.generated Sat Jun 14 22:38:08 CST 2025
     */
    private String agentName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ea_agent.analysis_model
     *
     * @mbg.generated Sat Jun 14 22:38:08 CST 2025
     */
    private String analysisModel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ea_agent.tool_model
     *
     * @mbg.generated Sat Jun 14 22:38:08 CST 2025
     */
    private String toolModel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ea_agent.agent_desc
     *
     * @mbg.generated Sat Jun 14 22:38:08 CST 2025
     */
    private String agentDesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ea_agent.id
     *
     * @return the value of ea_agent.id
     *
     * @mbg.generated Sat Jun 14 22:38:08 CST 2025
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ea_agent.id
     *
     * @param id the value for ea_agent.id
     *
     * @mbg.generated Sat Jun 14 22:38:08 CST 2025
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ea_agent.agent_name
     *
     * @return the value of ea_agent.agent_name
     *
     * @mbg.generated Sat Jun 14 22:38:08 CST 2025
     */
    public String getAgentName() {
        return agentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ea_agent.agent_name
     *
     * @param agentName the value for ea_agent.agent_name
     *
     * @mbg.generated Sat Jun 14 22:38:08 CST 2025
     */
    public void setAgentName(String agentName) {
        this.agentName = agentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ea_agent.analysis_model
     *
     * @return the value of ea_agent.analysis_model
     *
     * @mbg.generated Sat Jun 14 22:38:08 CST 2025
     */
    public String getAnalysisModel() {
        return analysisModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ea_agent.analysis_model
     *
     * @param analysisModel the value for ea_agent.analysis_model
     *
     * @mbg.generated Sat Jun 14 22:38:08 CST 2025
     */
    public void setAnalysisModel(String analysisModel) {
        this.analysisModel = analysisModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ea_agent.tool_model
     *
     * @return the value of ea_agent.tool_model
     *
     * @mbg.generated Sat Jun 14 22:38:08 CST 2025
     */
    public String getToolModel() {
        return toolModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ea_agent.tool_model
     *
     * @param toolModel the value for ea_agent.tool_model
     *
     * @mbg.generated Sat Jun 14 22:38:08 CST 2025
     */
    public void setToolModel(String toolModel) {
        this.toolModel = toolModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ea_agent.agent_desc
     *
     * @return the value of ea_agent.agent_desc
     *
     * @mbg.generated Sat Jun 14 22:38:08 CST 2025
     */
    public String getAgentDesc() {
        return agentDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ea_agent.agent_desc
     *
     * @param agentDesc the value for ea_agent.agent_desc
     *
     * @mbg.generated Sat Jun 14 22:38:08 CST 2025
     */
    public void setAgentDesc(String agentDesc) {
        this.agentDesc = agentDesc;
    }
}